#!/usr/bin/env bash

GCC_TOOLCHAIN_PATH=$PWD/../arm-gnu-toolchain
CROSS_COMPILER_PREFIX=aarch64-none-linux-gnu
CROSS_COMPILER_SYSROOT=$GCC_TOOLCHAIN_PATH/$CROSS_COMPILER_PREFIX/libc

GEM5_PATH=$PWD/gem5
M5_BUILD_PATH=build/arm64/out/m5
M5_LIB_PATH=$GEM5_PATH/util/m5/${M5_BUILD_PATH/\/m5/}

PATH=`sed 's|'$GCC_TOOLCHAIN_PATH'[^:]\+:||g' <<<$PATH`

export GCC_TOOLCHAIN_PATH
export CROSS_COMPILER_PREFIX
export CROSS_COMPILER_SYSROOT
export PATH=$GCC_TOOLCHAIN_PATH/bin:$PATH
export GEM5_PATH
export M5_BUILD_PATH
export M5_LIB_PATH
